### ISSUE TITLE
panic error in pager view for small height of terminal

### ISSUE THREAD

**Issue by multithread3** [charmbracelet/bubbles#20]
Tried with https://github.com/charmbracelet/bubbletea/tree/master/examples/pager

If the height is less than 6, than it got panic in the pager view:

height=10
![image](https://user-images.githubusercontent.com/71344858/97114523-f7998c80-172b-11eb-8fcb-1709b5995752.png)

height=6
![image](https://user-images.githubusercontent.com/71344858/97114571-3d565500-172c-11eb-84aa-7d94175bd31f.png)

height=5
got panic errors:
```
bash-3.2$ ./one-pager 
Caught panic:

runtime error: slice bounds out of range [:-1]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack(0x56, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/debug/stack.go:16 +0x25
github.com/charmbracelet/bubbletea.(*Program).Start.func1(0xc0000743c0)
	/Users/mas/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.12.0/tea.go:119 +0xd3
panic(0x1104200, 0xc0000b4000)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:969 +0x175
github.com/charmbracelet/bubbles/viewport.Model.visibleLines(...)
	/Users/mas/go/pkg/mod/github.com/charmbracelet/bubbles@v0.7.0/viewport/viewport.go:81
github.com/charmbracelet/bubbles/viewport.View(0x78, 0xffffffffffffffff, 0x0, 0x3, 0x0, 0xc000080480, 0x45, 0x45, 0x0, 0x45)
	/Users/mas/go/pkg/mod/github.com/charmbracelet/bubbles@v0.7.0/viewport/viewport.go:366 +0x24d
main.model.View(0xc000136000, 0x642, 0x1, 0x78, 0xffffffffffffffff, 0x0, 0x3, 0x0, 0xc000080480, 0x45, ...)
	/Users/mas/go/src/bitbucket.org/demo-learn/app/one-pager/main.go:157 +0x56e
github.com/charmbracelet/bubbletea.(*Program).Start(0xc0000743c0, 0x0, 0x0)
	/Users/mas/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.12.0/tea.go:216 +0x67d
main.main()
	/Users/mas/go/src/bitbucket.org/demo-learn/app/one-pager/main.go:66 +0x2d4
```

**Comment by meowgorithm** [comment]
Thanks so much for the report! This is now fixed in `master`. We're expecting to tag a point release later today so this fix will be in the next version (`v0.7.2`).
